---
- name: Install RPM packages
  dnf:
    name:
      - gcc
      - libffi-devel
      - libpq-devel
      - krb5-devel
      - python3-cryptography
      - python3-devel
      - python3-pip
      - python3-virtualenv
    state: present

- name: Install the .bashrc
  copy:
    src: bashrc
    dest: /home/vagrant/.bashrc
    mode: 0644
    owner: vagrant
    group: vagrant

# - name: Install poetry Python package
#   command: pip install poetry
#
# - name: install python deps
#   become_user: vagrant
#   command:
#     cmd: poetry install
#     chdir: fedbadges

- name: prepare virtualenv
  file:
    path: "{{ venv }}"
    state: directory
    owner: vagrant
    group: vagrant

- name: install some python build deps
  become_user: vagrant
  pip:
    virtualenv: "{{ venv }}"
    name: cython

- name: install python deps from synced dirs
  become_user: vagrant
  pip:
    chdir: "{{ item }}"
    editable: true
    virtualenv: "{{ venv }}"
    name: .
  loop:
    - tahrir-api
    - tahrir
    - fedbadges

- name: Install the configuration file
  copy:
    src: config.toml
    dest: /etc/fedora-messaging/fedbadges.toml
    owner: root
    group: vagrant
    mode: 0640

- name: Copy other files
  copy:
    src: "{{ item }}"
    dest: /home/vagrant/{{ item }}
    owner: vagrant
    group: vagrant
    mode: 0640
  loop:
    - "tahrir.cfg"
    - "alembic.ini"

- name: Create or update the database
  command: "{{ venv }}/bin/tahrir-sync-db /home/vagrant/tahrir.cfg"
  become: yes
  become_user: vagrant
  args:
    chdir: /home/vagrant/tahrir

- name: Install the systemd unit files
  copy:
    src: "{{ item }}.service"
    dest: /etc/systemd/system/{{ item }}.service
    mode: 0644
  loop:
    - fedbadges
    - tahrir

- name: Start the service using systemd
  systemd:
    state: started
    name: "{{ item }}"
    daemon_reload: yes
    enabled: yes
  loop:
    - fedbadges
    - tahrir
